import bcrypt from "bcryptjs";
import { pool,query } from "../src/db.js";
const pass=await bcrypt.hash("Password123!",12);
async function main(){
await query("TRUNCATE certificates,live_classes,notifications,reviews,bookmarks,progress,enrollments,exam_attempts,exams,quiz_attempts,questions,quizzes,articles,lesson_resources,lessons,topics,courses,subscriptions,payments,learner_profiles,teacher_profiles,users,subjects RESTART IDENTITY CASCADE");
const roles=(await query("SELECT id,name FROM roles")).rows;
const role=n=>roles.find(x=>x.name===n).id;
const teachers=[];for(const [name,email] of [["Dr. Jane Mwangi","teacher@learnsci.test"],["Mr. Peter Otieno","teacher2@learnsci.test"],["Ms. Amina Noor","teacher3@learnsci.test"]]){const r=await query("INSERT INTO users(name,email,password_hash,role_id) VALUES($1,$2,$3,$4) RETURNING id",[name,email,pass,role("teacher")]);teachers.push(r.rows[0].id);await query("INSERT INTO teacher_profiles(user_id,bio,qualification) VALUES($1,$2,$3)",[r.rows[0].id,"Experienced science educator and curriculum specialist.","Bachelor of Education"]);} 
const learner=await query("INSERT INTO users(name,email,password_hash,role_id) VALUES($1,$2,$3,$4) RETURNING id",["John Kamau","learner@learnsci.test",pass,role("learner")]);await query("INSERT INTO learner_profiles(user_id,education_level) VALUES($1,'Secondary')",[learner.rows[0].id]);
const admin=await query("INSERT INTO users(name,email,password_hash,role_id) VALUES($1,$2,$3,$4) RETURNING id",["LearnSci Admin","admin@learnsci.test",pass,role("admin")]);
const subjects=[["Mathematics","mathematics","Algebra, geometry, statistics and mathematical reasoning.","blue"],["Chemistry","chemistry","Matter, reactions, organic chemistry and laboratory reasoning.","purple"],["Physics","physics","Mechanics, energy, waves, electricity and modern physics.","orange"],["Biology","biology","Cells, genetics, ecology, physiology and evolution.","green"]];
const sub={};for(const s of subjects){const r=await query("INSERT INTO subjects(name,slug,description,color) VALUES($1,$2,$3,$4) RETURNING id",[...s]);sub[s[1]]=r.rows[0].id;}
const topicNames={
mathematics:["Algebra","Functions","Linear Equations","Quadratic Equations","Geometry","Trigonometry","Statistics","Probability","Sequences","Calculus"],
chemistry:["Atomic Structure","Periodic Table","Chemical Bonding","Mole Concept","Stoichiometry","Acids & Bases","Organic Chemistry","Energetics","Rates of Reaction","Electrochemistry"],
physics:["Measurement","Motion","Forces","Energy","Momentum","Waves","Thermal Physics","Electricity","Magnetism","Modern Physics"],
biology:["Cell Structure","Biological Molecules","Enzymes","Genetics","Evolution","Ecology","Human Nutrition","Respiration","Reproduction","Homeostasis"]};
let lessonId=0;
for(const [slug,names] of Object.entries(topicNames)){for(let i=0;i<names.length;i++){const t=await query("INSERT INTO topics(subject_id,name,slug,description) VALUES($1,$2,$3,$4) RETURNING id",[sub[slug],names[i],`${slug}-${i+1}`,`Core ${names[i]} concepts with guided examples and practice.`]);if(i<5){const l=await query("INSERT INTO lessons(topic_id,title,slug,content_html,duration_minutes,level,is_premium,published,created_by) VALUES($1,$2,$3,$4,$5,'Secondary',$6,true,$7) RETURNING id",[t.rows[0].id,`${names[i]}: Core Concepts`,`${slug}-${i+1}-core-concepts`,`<h2>${names[i]}</h2><p>This lesson introduces the essential ideas, vocabulary and worked reasoning for ${names[i]}.</p><p><strong>Study approach:</strong> read the concept, work through the example, then complete the practice questions.</p>`,18+i*2,true,teachers[i%teachers.length]]);lessonId=l.rows[0].id;await query("INSERT INTO lesson_resources(lesson_id,title,type,url) VALUES($1,$2,'PDF',$3)",[lessonId,`${names[i]} revision notes`,`https://example.com/learnsci/${slug}/${i+1}.pdf`]);}}}
for(let i=1;i<=10;i++){const c=await query("INSERT INTO courses(subject_id,title,slug,description,is_premium,published,created_by) VALUES($1,$2,$3,$4,true,true,$5) RETURNING id",[sub[subjects[(i-1)%4][1]],`LearnSci Course ${i}`,`course-${i}`,`Structured course ${i} for progressive mastery.`,teachers[i%3]]);const q=await query("INSERT INTO quizzes(title,description,course_id,is_published) VALUES($1,$2,$3,true) RETURNING id",[`Revision Quiz ${i}`,"Ten-question premium revision quiz.",c.rows[0].id]);for(let j=0;j<10;j++)await query("INSERT INTO questions(quiz_id,prompt,options,correct_option,position) VALUES($1,$2,$3,$4,$5)",[q.rows[0].id,`Question ${j+1}: Which statement best represents the concept being tested?`,JSON.stringify(["Option A","Option B","Option C","Option D"]),j%4,j]);}
for(let i=1;i<=10;i++)await query("INSERT INTO articles(title,slug,excerpt,content_html,subject_id,author_id,status,published_at) VALUES($1,$2,$3,$4,$5,$6,'published',NOW()-($7||' days')::interval)",[`Study Strategy ${i}: Building Better Science Habits`,`study-strategy-${i}`,"Practical guidance for learning science consistently.",`<h2>Build a repeatable study system</h2><p>Use retrieval practice, worked examples, spaced review and deliberate practice.</p>`,sub[subjects[(i-1)%4][1]],teachers[i%3],i]);
console.log("Seed complete: 4 subjects, 40 topics, 20 premium lessons, 10 articles, 10 quizzes, 3 teachers, 1 learner and 1 admin.");
await pool.end();
}
main().catch(e=>{console.error(e);process.exit(1)});
